tunnel: ${{ secrets.TUNNEL_ID_SERVER1 }}
credentials-file: ./credentials.json
ingress:
  - hostname: api.leadbaseai.in
    path: /server1/*
    service: http://localhost:5000
  - service: http_status:404
