name: Serve Flask API via Tunnel

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours (00:00, 06:00, 12:00, 18:00)

jobs:
  backend:
    runs-on: ubuntu-latest
    timeout-minutes: 357  # Just under 6 hours

    steps:
      - name: Checkout repo with push access
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}  # Classic token with repo access

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          pip install flask flask-cors PyGithub

      - name: Decode Cloudflare credentials
        run: echo "${{ secrets.CLOUDFLARE_CERT }}" | base64 -d > credentials.json

      - name: Download cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          mv cloudflared-linux-amd64 cloudflared

      - name: Launch Flask API + Tunnel
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          python server.py &
          sleep 5
          ./cloudflared tunnel --config config.yml run
