name: Serve Flask API via Tunnel

on:
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout repo with push access
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}  # Required for database push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          pip install flask flask-cors PyGithub

      - name: Decode Cloudflare credentials
        run: echo "${{ secrets.CLOUDFLARE_CERT }}" | base64 -d > credentials.json

      - name: Download cloudflared binary
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O /tmp/cloudflared
          chmod +x /tmp/cloudflared
          sudo mv /tmp/cloudflared /usr/local/bin/cloudflared

      - name: Start Flask + Tunnel
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SERVER_PREFIX: ${{ secrets.SERVER_PREFIX }}  # e.g., /server1
        run: |
          export FLASK_APP=server.py
          python -m flask run --host=0.0.0.0 --port=5000 &

          sleep 5

          cloudflared tunnel --config config.yml run
