name: Serve Flask API via Tunnel

on:
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Flask
        run: pip install flask flask-cors

      - name: Decode credentials.json
        run: echo "${{ secrets.CLOUDFLARE_CERT }}" | base64 -d > credentials.json

      - name: Download cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          mv cloudflared-linux-amd64 cloudflared

      - name: Start Flask + Tunnel
        run: |
          python server.py &
          sleep 5
          ./cloudflared tunnel --config config.yml run
